### ISSUE TITLE
An unhandled exception occurred: Unexpected token

### ISSUE THREAD

**Issue by miguelsmuller** [ngneat/tailwind#102]
## I'm submitting a...
<pre><code>[x] Bug report
[x] Support request
</code></pre>

## Current behavior
Actually i'm not sure the problem could be with @ ngneat / tailwind.
After successfully using the package I am having trouble getting it to continue. When I run the command "ng serve" I get the following error return:
<pre><code>An unhandled exception occurred: Unexpected token (54:12)
See "C:\Users\MIGUEL~1\AppData\Local\Temp\ng-JkyjcC\angular-errors.log" for further details.</code></pre>

seeing the informed log file I have the following:

<pre><code>[error] SyntaxError: Unexpected token (54:12)
    at _class.pp$4.raise (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:2927:15)
    at _class.pp.unexpected (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:698:10)
    at _class.pp.semicolon (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:675:66)
    at _class.pp$1.parseExpressionStatement (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:1154:10)
    at _class.pp$1.parseStatement (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:889:26)
    at _class.parseStatement (FOLDER\node_modules\acorn-node\lib\dynamic-import\index.js:65:118)
    at _class.pp$1.parseTopLevel (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:755:23)
    at _class.parse (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:555:17)
    at Function.parse (FOLDER\node_modules\acorn-node\node_modules\acorn\dist\acorn.js:578:37)
    at Object.parse (FOLDER\node_modules\acorn-node\index.js:30:28)
    at parse (FOLDER\node_modules\detective\index.js:22:18)
    at Function.exports.find (FOLDER\node_modules\detective\index.js:47:15)
    at module.exports (FOLDER\node_modules\detective\index.js:26:20)
    at createModule (FOLDER\pousada-muller-site\node_modules\tailwindcss\lib\lib\getModuleDependencies.js:21:43)
    at getModuleDependencies (FOLDER\pousada-muller-site\node_modules\tailwindcss\lib\lib\getModuleDependencies.js:29:22)
    at FOLDER\node_modules\tailwindcss\lib\index.js:72:42</code></pre>

## Environment
<pre><code>@angular/cli      11.2.10
@angular/material 11.2.10
@schematics/angular  11.2.10
@schematics/update  0.1102.10

For Tooling issues:
- Node version: Node: 14.16.0
- Platform:  Windows 10
</code></pre>
### package.json
<code><pre>
{
  "name": "pousada-muller-site",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --aot --build-optimizer --vendor-chunk --source-map=false",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.11",
    "@angular/cdk": "^11.2.10",
    "@angular/common": "~11.2.11",
    "@angular/compiler": "~11.2.11",
    "@angular/core": "~11.2.11",
    "@angular/forms": "~11.2.11",
    "@angular/material": "^11.2.10",
    "@angular/platform-browser": "~11.2.11",
    "@angular/platform-browser-dynamic": "~11.2.11",
    "@angular/router": "~11.2.11",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "owl.carousel2": "^2.2.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.10",
    "@angular/cli": "~11.2.10",
    "@angular/compiler-cli": "~11.2.11",
    "@ngneat/tailwind": "^7.0.3",
    "@tailwindcss/aspect-ratio": "0.2.0",
    "@tailwindcss/forms": "0.3.2",
    "@tailwindcss/line-clamp": "0.2.0",
    "@tailwindcss/typography": "0.4.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "autoprefixer": "^10.2.5",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "postcss": "^8.2.13",
    "protractor": "~7.0.0",
    "tailwindcss": "^2.1.2",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
</code></pre>

**Comment by miguelsmuller** [comment]
I found out that the error was in the **tailwind.config.js** file.
It had the wrong closed object.
