### ISSUE TITLE
Storybook in Nx Repo TypeError: Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by ajonp** [ngneat/tailwind#72]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I successfully have tailwind working in an Nx 11.2 application. However I want to create a Design Library in Storybook and use tailwind for styling. When adding the same configuration to the storybook webpack config I receive an error.

![image](https://user-images.githubusercontent.com/3102249/107025723-cba09500-6777-11eb-9609-7fef0603631b.png)

```
> nx run kitten:storybook 
info => Loading presets
info => Loading presets
info => Loading 1 config file in "libs/kitten/.storybook"
info => Adding stories defined in "libs/kitten/.storybook/main.js"
info => Found custom tsconfig.json
info => Using angular project 'blackcat' for configuring Storybook.
info => Loading angular-cli config.
info => Get angular-cli webpack config.
info => Loading custom Webpack config (full-control mode).
ERR! TypeError: Cannot read property 'rules' of undefined
ERR!     at addTailwindPlugin (/Users/ajonp/web/codingcatdev/node_modules/@ngneat/tailwind/src/add-tailwind-plugin.js:14:45)
ERR!     at module.exports (/Users/ajonp/web/codingcatdev/.storybook/webpack.config.js:11:3)
ERR!     at module.exports (/Users/ajonp/web/codingcatdev/libs/kitten/.storybook/webpack.config.js:9:18)
ERR!     at Object.webpack (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:41:12)
ERR!     at async startPreview (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/dev-server.js:408:23)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/dev-server.js:505:29)
ERR!     at async Object.buildDevStandalone (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/build-dev.js:317:33)
ERR!  TypeError: Cannot read property 'rules' of undefined
ERR!     at addTailwindPlugin (/Users/ajonp/web/codingcatdev/node_modules/@ngneat/tailwind/src/add-tailwind-plugin.js:14:45)
ERR!     at module.exports (/Users/ajonp/web/codingcatdev/.storybook/webpack.config.js:11:3)
ERR!     at module.exports (/Users/ajonp/web/codingcatdev/libs/kitten/.storybook/webpack.config.js:9:18)
ERR!     at Object.webpack (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:41:12)
ERR!     at async startPreview (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/dev-server.js:408:23)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/dev-server.js:505:29)
ERR!     at async Object.buildDevStandalone (/Users/ajonp/web/codingcatdev/node_modules/@storybook/core/dist/server/build-dev.js:317:33)
```

## Expected behavior

I should be able to use tailwind within a library for storybook, as well as use the components within Angular.

## Minimal reproduction of the problem with instructions

https://github.com/CodingCatDev/blackcat

- npm i
- nx run kitten:storybook or npx nx run kitten:storybook 

## What is the motivation / use case for changing the behavior?

I would like to be able to use tailwind within Storybook and then import those components within my Angular project that has Tailwind.

## Environment

<pre><code>
Angular CLI: 11.0.7
Node: 14.15.1
OS: darwin x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5

nx --version                                                                                              ✔ 
11.2.10

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.15.1
- Platform:  Mac

Others:
VSCode
</code></pre>

**Comment by ajonp** [comment]
My apologies I was at the root storybook webpack, and should have been within my library, feel free to close.
![image](https://user-images.githubusercontent.com/3102249/107028978-479cdc00-677c-11eb-8401-d346446de52c.png)
