### ISSUE TITLE
An unhandled exception occurred: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by LALauw** [ngneat/tailwind#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## I'm submitting a problem when running in a new angular project. 

<pre><code>
[error] TypeError: Cannot read property 'kind' of undefined
    at Object.getExternalModuleName (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:15175:45)
    at collectModuleReferences (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101288:45)
    at collectExternalModuleReferences (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101277:17)
    at processImportedModules (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101843:13)
    at findSourceFile (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101590:17)
    at D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101419:85
    at getSourceFileFromReferenceWorker (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101386:34)
    at processSourceFile (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101419:13)
    at processRootFile (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101242:13)
    at D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101817:21
    at Object.forEach (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:317:30)
    at processLibReferenceDirectives (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101812:16)
    at findSourceFile (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101587:21)
    at D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101419:85
    at getSourceFileFromReferenceWorker (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101386:34)
    at processSourceFile (D:\3 HHS\test_tailwind\test-tailwind\node_modules\typescript\lib\typescript.js:101419:13)

</code></pre>

## Current behavior

I created a brand new angular project. Then I ran ng add @ngneat/tailwind command and selected the desired settings. 
After that I ran ng serve, but the error above comes up. 

I also tried npm install after that but the problem still persisted. How do I fix this?

**Comment by pinguinosod** [comment]
I got the same error.
I ran `ng update @angular/cli @angular/core` so angular got updated to version 11.
Then I was able to install tailwind with `ng add @ngneat/tailwind`

I hope it helps

**Comment by nartc** [comment]
Thanks @pinguinosod for the workaround.
