### ISSUE TITLE
ng serve throws error

### ISSUE THREAD

**Issue by webdagger** [ngneat/tailwind#8]
## I'm submitting a bug report

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behaviour
After creating a new angular project and immediately <code>running ng add @ngneat/tailwind</code>
All works as expected and I select scss.
When I serve the project, it raises issues and fails to compile. 
  

It starts to warn about postcss first but this does not break it yet 

> Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.34, but postcss-functions uses 6.0.23. Perhaps this is the source of the error below.

The app then fails to compile, throwing. 
<br />
ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./node_modules/postcss-loader/dist/cjs.js??ref--18!./src/styles.scss)
<br />
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'charCodeAt' of undefined
    at module.exports (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/node_modules/postcss-value-parser/lib/parse.js:17:20)
<br />
    at new ValueParser (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/node_modules/postcss-value-parser/lib/index.js:7:18)<br />
    at ValueParser (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/node_modules/postcss-value-parser/lib/index.js:10:10)<br />
    at transformValue (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/dist/lib/transformer.js:20:55)<br />
    at /home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/dist/lib/transformer.js:74:24
    at /home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/dist/index.js:45:18
    at /home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-scss/node_modules/postcss/lib/container.js:82:18<br />
    at Root.each (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-scss/node_modules/postcss/lib/container.js:68:16)<br />
    at Root.walk (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-scss/node_modules/postcss/lib/container.js:79:17)<br />
    at /home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/postcss-functions/dist/index.js:44:7
    at LazyResult.run (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:288:14)<br />
    at LazyResult.asyncTick (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:212:26)<br />
    at LazyResult.asyncTick (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:225:14)<br />
    at /home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:254:14<br />
    at new Promise (<anonymous>)
    at LazyResult.async (/home/mipo/projects/learning/angular-bank/app2/bank-mvp/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:250:23)<br />

## Expected behavior
I expect the app to run and be able to use tailwind in the templates.

## Minimal reproduction of the problem with instructions

1. Create new Angular project
2. Run <code>ng add @ngneat/tailwind</code>

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem

## Environment

<pre><code>
Angular version: 10.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by webdagger** [comment]
This only affects scss. 
I created a new project selecting css and it works fine.

**Comment by lhargil** [comment]
In my quick test, it looks like `postcss-scss@3.x.x` breaks during the build. Reverting to version `postcss-scss@2.1.1` can solve the issue.

**Comment by nartc** [comment]
This is actually a bug with `postcss`, particularly `postcss-scss`.
https://github.com/tailwindlabs/tailwindcss/issues/2426
