### ISSUE TITLE
Tailwind JIT support

### ISSUE THREAD

**Issue by Meldiron** [ngneat/tailwind#83]
**Is your feature request related to a problem? Please describe.**
Tailwind recently added JIT to speed-up the development process and allow us to use new features. It would be great to have this implemented.

**Describe the solution you'd like**
This could be an option when doing `ng add`

Info: https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css

**Comment by NetanelBasal** [comment]
We need to replace `tailwind` with `@tailwindcss/jit` and add `TAILWIND_MODE=watch` environment variable.

**Comment by Meldiron** [comment]
I tried to replace `tailwind` with `@tailwindcss/jit` and run using `TAILWIND_MODE=watch ng serve` but it resulted in error:
```
Locale data for 'en-SK' cannot be found.  Using locale data for 'en'.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |    Size
main.js             | main          | 0 bytes
polyfills.js        | polyfills     | 0 bytes
runtime.js          | runtime       | 0 bytes
styles.js           | styles        | 0 bytes
vendor.js           | vendor        | 0 bytes

                    | Initial Total | 0 bytes

Build at: 2021-03-24T09:07:32.711Z - Hash: a0d540b7f6baea125e71 - Time: 10207ms

Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:11:24)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at /Users/meldiron/Desktop/stream-cv/Admin/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/meldiron/Desktop/stream-cv/Admin/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/meldiron/Desktop/stream-cv/Admin/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/meldiron/Desktop/stream-cv/Admin/node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/index.js:104:7)
```

If anyone here is experienced enough to debug, please follow-up and we can come up with a solution.

**Comment by vltansky** [comment]
https://github.com/tailwindlabs/tailwindcss-jit#getting-started

> If you are using autoprefixer, make sure you are on the latest version using npm install -D autoprefixer@latest — there's a bug in older versions that makes it incompatible with this library.

try `npm install -D autoprefixer@latest`

**Comment by Meldiron** [comment]
After updating autoprefixter to latest (`"autoprefixer": "^10.2.5",`), I still get error `RangeError: Maximum call stack size exceeded` in `/src/styles.scss`.

My `styles.scss` is:
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

**Comment by NetanelBasal** [comment]
It worked for me.

**Comment by Meldiron** [comment]
Oh.. Can we share `package.json` and `tailwind.config.js` to see what may be the cause?

package.json:
```
{
  "name": "stream-cv-admin",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "dev": "ng serve --port 4200",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "gen:api": "swagger2js generate http://localhost:3000/public/swagger.json -t typescript -c API > src/app/services/API.ts",
    "gen:lang": "ng extract-i18n --format arb --ivy --out-file src/locale/messages.en-SK.json && node cli/lang_upload.js",
    "lang:up": "npm run gen:lang && localazy upload",
    "lang:down": "localazy download && node cli/lang_download.js",
    "dev:sk": "ng serve --configuration=sk",
    "dev:en": "ng serve --configuration=en"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "@ngneat/tailwind": "^6.0.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-webpack-plugin": "^5.3.1",
    "ngx-cookie-service": "^11.0.2",
    "rxjs": "~6.6.0",
    "swagger-js-codegen": "https://github.com/Meldiron/swagger-js-codegen",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^11.1.0",
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.1.0",
    "@angular/localize": "^11.1.2",
    "@tailwindcss/aspect-ratio": "0.2.0",
    "@tailwindcss/forms": "0.2.1",
    "@tailwindcss/jit": "^0.1.4",
    "@tailwindcss/line-clamp": "0.2.0",
    "@tailwindcss/typography": "0.4.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "autoprefixer": "^10.2.5",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "postcss": "^8.2.8",
    "protractor": "~7.0.0",
    "tailwindcss": "^2.0.4",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }
}
```

tailwind.config.js:
```
const colors = require("tailwindcss/colors");

module.exports = {
  prefix: "",
  purge: {
    content: ["./src/**/*.{html,ts}"]
  },
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        orange: colors.orange,
        "light-blue": colors.lightBlue,
        teal: colors.teal,
        rose: colors.rose
      }
    }
  },
  variants: {
    extend: {
      // opacity: ["disabled"]
    }
  },
  plugins: [
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/line-clamp"),
    require("@tailwindcss/typography")
  ]
};
```

**Comment by NetanelBasal** [comment]
You need to wait for this feature. As I said we need to replace `tailwindcss` with `tailwindcss/jit`. I tested it locally.

**Comment by Meldiron** [comment]
I tried to replace it locally also, but got error. Well, never mind then, I will wait for an official update from your side.

**Comment by TryHardDood** [comment]
@Meldiron You can use what I'm currently using as a workaround until we get the official support.
It only works from Angular 11.2 and up.

https://github.com/TryHardDood/ngx-tailwind

**Comment by TryHardDood** [comment]
TailwindCSS v2.1 is released, now you can use the `mode: 'jit'` option to enable JIT without installing any extra packages. 
However the TAILWIND_MODE=watch enviroment variable is still needed.

**Comment by nartc** [comment]
v7 has been released which will provide support JIT mode for new projects. Please take a look at https://github.com/ngneat/tailwind/compare/v6.0.3...v7.0.0 for changes. Closing
